version: "3"

includes:
  lib:
    taskfile: ../common/Taskfile.yaml
    flatten: true

tasks:
  # rust pkgs
  ripgrep: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.ripgrep
  starship: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.starship
  eza: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.eza
  bat: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.bat
  atuin: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.atuin
  # ruff: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.ruff
  fd: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.fd
  git-absorb: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.git-absorb

  # others
  silver-searcher: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.silver-searcher
  llvmPackages_18.clang-unwrapped: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.llvmPackages_18.clang-unwrapped

  aria2:
    - task: setup-old-2411
    - nix-env -I old=$HOME/.nix-defexpr/channels/old -p ~/nix/profiles/prebuilt -iA old.pkgsStatic.aria2
