version: "3"

includes:
  lib:
    taskfile: ../common/Taskfile.yaml
    flatten: true

tasks:
  silver-searcher: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.silver-searcher

  llvmPackages_18.clang-unwrapped: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.llvmPackages_18.clang-unwrapped

  ruff: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.ruff

  # go pkgs
  fzf: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.fzf
  gdu: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.gdu
  git-lfs: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.git-lfs
  go-task: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.go-task
  gost: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.gost
  shfmt: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.shfmt
  buildifier: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.buildifier

  # rust pkgs
  starship: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.starship
  eza: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.eza
  bat: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.bat
  atuin: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.atuin
  # ruff: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.ruff
  fd: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.fd
  git-absorb: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.git-absorb

  aria2:
    - task: setup-old-2411
    - nix-env -I old=$HOME/.nix-defexpr/channels/old -p ~/nix/profiles/prebuilt -iA old.pkgsStatic.aria2
