version: "3"

tasks:
  setup:
    cmds:
      - nix-channel --add https://nixos.org/channels/nixos-25.05 nixpkgs
      - nix-channel --update
      - nix-channel --list
      - mkdir -p ~/nix/profiles

  setup-extra:
    # - nix-channel --add https://nixos.org/channels/nixos-24.05 old
    # - nix-channel --add https://nixos.org/channels/nixpkgs-unstable unstable
    # - nix-channel --add https://github.com/NixOS/nixpkgs/archive/master.tar.gz master
    # - nix-channel --add https://github.com/NixOS/nixpkgs/archive/staging.tar.gz staging
    - nix-channel --add https://github.com/tobim/nixpkgs/archive/refs/heads/pkgs/git-static.tar.gz git_fix
    - nix-channel --update
  setup-old-2411:
    - nix-channel --add https://nixos.org/channels/nixos-24.11 old
    - nix-channel --update
  setup-old:
    - nix-channel --add https://nixos.org/channels/nixos-24.05 old
    - nix-channel --update
  setup-unstable:
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable unstable
    - nix-channel --update
  setup-master:
    - nix-channel --add https://github.com/NixOS/nixpkgs/archive/master.tar.gz master
    - nix-channel --update
  setup-staging:
    - nix-channel --add https://github.com/NixOS/nixpkgs/archive/staging.tar.gz staging
    - nix-channel --update

  lua: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.lua
  bash: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.bash
  binutils: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.binutils-unwrapped
  bison: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.bison
  bzip2: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.bzip2
  connect: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.connect
  ethtool: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.ethtool
  exiftool: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.exiftool
  findutils: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.findutils
  flex: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.flex
  gawk: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gawk
  gdb: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gdb
  getopt: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.getopt
  gettext: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gettext
  git-extras: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.git-extras
  gnugrep: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnugrep
  gnumake: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnumake
  gnupatch: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnupatch
  gnupg: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnupg
  gnused: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnused
  gnutar: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnutar
  gzip: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gzip
  indent: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.indent
  inetutils: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.inetutils
  iproute2: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.iproute2
  iptables: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.iptables
  iputils: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.iputils
  jq: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.jq
  krb5: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.krb5
  less: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.less
  libcap: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.libcap
  lsb-release: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.lsb-release
  lsof: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.lsof
  m4: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.m4
  man: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.man
  ncdu_1: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.ncdu_1
  netcat: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.netcat
  nettools: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.nettools
  ninja: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.ninja
  nixfmt-rfc-style: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.nixfmt-rfc-style
  nixpkgs-fmt: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.nixpkgs-fmt
  numactl: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.numactl
  openssl: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.openssl.bin
  parallel: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.parallel
  patchelf: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.patchelf
  perl: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.perl
  pkg-config: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.pkg-config-unwrapped
  procps: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.procps
  procs: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.procs
  protobuf_24: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.protobuf_24
  protobuf_25: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.protobuf_25
  protobuf_28: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.protobuf_28
  rsync: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.rsync
  smartmontools: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.smartmontools
  snappy: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.snappy
  strace: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.strace
  tmux: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.tmux
  tree: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.tree
  tzdata: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.tzdata.out
  unzip: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.unzip
  util-linux: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.util-linux
  xxd: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.unixtools.xxd
  xz: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.xz
  zip: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.zip
  zlib-ng: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.zlib-ng
  zlib: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.zlib
  zstd: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.zstd

  # wrapped
  autoconf: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix autoconf
  automake: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix automake
  coreutils: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix coreutils
  curl: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix curl
  file: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix file
  glibcLocales: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix glibcLocales
  libtool: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix libtool
  makeself: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix makeself
  miniserve: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix miniserve
  openssh_gssapi: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix openssh_gssapi
  rime-extra: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix rime-extra
  tmux-bundle: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix tmux-bundle
  vim-bundle: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix vim-bundle
  vim: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix vim
  wget: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix wget
  zsh-bundle: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix zsh-bundle
  zsh: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix zsh

  # pypkgs
  dool: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix dool
  git-filter-repo: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix git-filter-repo
  netron: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix netron

  # patched
  diffutils: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix diffutils
  zellij: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix zellij
  cmake: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix cmake
  git: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix git --keep-failed
  # gettext: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix gettext --keep-failed

  # new
  zsh-extra: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix zsh-extra
  nsight-systems: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix nsight-systems
  cacert: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix cacert
  python311: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix python311
  tmux-extra: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix tmux-extra
  vim-extra: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix vim-extra

  protobuf_3_8_0:
    - task: setup-old
    - nix-env -I old=$HOME/.nix-defexpr/channels/old -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix protobuf_3_8_0

  protobuf_3_9_2:
    - task: setup-old
    - nix-env -I old=$HOME/.nix-defexpr/channels/old -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix protobuf_3_9_2

  # go pkgs
  bazelisk: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix bazelisk
  croc: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix croc
  fzf: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix fzf
  gdu: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix gdu
  gh: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix gh
  git-lfs: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix git_lfs
  go-task: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix go_task
  gost: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix gost
  shfmt: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix shfmt
  scc: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix scc
  dive: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix dive
  buildifier: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/gopkgs-without-cgo.nix buildifier
