version: "3"

tasks:
  setup:
    cmds:
      - nix-channel --add https://nixos.org/channels/nixos-24.11 nixpkgs
      - nix-channel --update
      - nix-channel --list
      - mkdir -p ~/nix/profiles

  setup-extra:
    - nix-channel --add https://nixos.org/channels/nixos-24.05 old
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable unstable
    - nix-channel --add https://github.com/NixOS/nixpkgs/archive/master.tar.gz master
    - nix-channel --add https://github.com/NixOS/nixpkgs/archive/staging.tar.gz staging
    - nix-channel --add https://github.com/tobim/nixpkgs/archive/refs/heads/pkgs/git-static.tar.gz git_fix
    - nix-channel --update
    - nix-channel --list
  # setup-old:
  #   - nix-channel --add https://nixos.org/channels/nixos-24.11 nixpkgs
  #   - nix-channel --update
  # setup-git_fix:
  #   - nix-channel --add https://github.com/tobim/nixpkgs/archive/refs/heads/pkgs/git-static.tar.gz nixpkgs
  #   - nix-channel --update

  aria2: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.aria2
  atuin: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.atuin
  autoconf: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.autoconf
  automake: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.automake
  gawk: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gawk
  getopt: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.getopt
  bash: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.bash
  bat: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.bat
  binutils: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.binutils
  bison: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.bison
  buildifier: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.buildifier
  bzip2: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.bzip2
  connect: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.connect
  # coreutils: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.coreutils
  curl: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.curl
  ethtool: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.ethtool
  eza: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.eza
  fd: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.fd
  file: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.file
  findutils: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.findutils
  flex: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.flex
  gdb: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gdb
  gettext: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gettext
  git-absorb: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.git-absorb
  git-extras: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.git-extras
  glibcLocales: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.glibcLocales
  gnugrep: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnugrep
  gnumake: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnumake
  gnupatch: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnupatch
  gnused: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnused
  gnutar: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gnutar
  gzip: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.gzip
  indent: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.indent
  inetutils: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.inetutils
  iproute2: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.iproute2
  iptables: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.iptables
  iputils: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.iputils
  jq: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.jq
  krb5: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.krb5
  less: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.less
  libcap: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.libcap
  libtool: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.libtool
  llvmPackages_18.clang-unwrapped: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.llvmPackages_18.clang-unwrapped
  lsb-release: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.lsb-release
  lsof: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.lsof
  m4: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.m4
  man: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.man
  miniserve: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.miniserve
  ncdu_1: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.ncdu_1
  netcat: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.netcat
  nettools: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.nettools
  ninja: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.ninja
  nixfmt-rfc-style: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.nixfmt-rfc-style
  nixpkgs-fmt: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.nixpkgs-fmt
  numactl: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.numactl
  openssh_gssapi: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.openssh_gssapi
  openssl: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.openssl.bin
  patchelf: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.patchelf
  perl: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.perl
  pkg-config: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.pkg-config
  procps: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.procps
  procs: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.procs
  protobuf_24: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.protobuf_24
  protobuf_25: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.protobuf_25
  protobuf_28: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.protobuf_28
  rsync: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.rsync
  snappy: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.snappy
  starship: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.starship
  strace: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.strace
  tmux: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.tmux
  tree: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.tree
  tzdata: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.tzdata.out
  unzip: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.unzip
  util-linux: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.util-linux
  vim: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.vim
  xxd: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.unixtools.xxd
  xz: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.xz
  zip: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.zip
  zlib-ng: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.zlib-ng
  zlib: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.zlib
  zstd: nix-env -p ~/nix/profiles/prebuilt -iA nixpkgs.pkgsStatic.zstd

  cacert: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix cacert
  vim-bundle: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix vim-bundle
  zsh-bundle: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix zsh-bundle
  rime-bundle: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix rime-bundle
  tmux-bundle: nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix tmux-bundle

  zsh:
    - task: setup-extra
    - nix-env -I old=$HOME/.nix-defexpr/channels/old -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix zsh_static

  coreutils:
    - nix-env -p ~/nix/profiles/prebuilt -iA -f ../../pkgs/default.nix coreutils_static
