# syntax=docker/dockerfile:1.9.0
FROM nixpkgs/nix-unstable:latest AS nixpkgs-builder

ENV NIX_PATH=nixpkgs=channel:nixos-24.11

RUN nix-channel --add https://github.com/NixOS/nixpkgs/archive/staging.tar.gz nixpkgs \
  && nix-channel --update

ARG PACKAGE_NAME=curl
RUN nix-env -iA nixpkgs.pkgsStatic.${PACKAGE_NAME}
