name: build llvm-tools

on:
  push:
    branches:
      - master
  # push:
  #   paths:
  #     - ".github/workflows/build.yaml"
  #     - "pkgs/**"
  #     - "tasks/**"
  #     - "scripts/**"
  workflow_dispatch:
    inputs:
      name:
        description: 'package name'
        default: ''
        required: false
        type: string
  # schedule:
  #   - cron: '0 0 - name: - name: 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        version:
          - 18
    steps:
      - run: echo "skip_steps=true" >> $GITHUB_ENV
      - run: echo "skip_steps=false" >> $GITHUB_ENV
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.name == 'clang-tools') || (github.event_name == 'push' && github.ref == 'refs/heads/master') }}

      - uses: actions/checkout@v4
        if: ${{ env.skip_steps != 'true' }}

      - run: ./docker/build.sh llvm_18 linux-x86_64
        if: ${{ env.skip_steps != 'true' }}

      - name: pack clang-format
        run: |
          mkdir -p tmp
          tar -x --gunzip -f llvm_18.linux-x86_64.tar.gz -C tmp --strip-components=1
          mkdir -p clang-format_18/bin
          cp tmp/bin/clang-format clang-format_18/bin/clang-format-18
          tar -c --gunzip -f clang-format_18.linux-x86_64.tar.gz clang-format_18
          mkdir -p lld_18/bin
          cp tmp/bin/lld lld_18/bin/lld-18
          tar -c --gunzip -f lld_18.linux-x86_64.tar.gz lld_18
        if: ${{ env.skip_steps != 'true' }}

      - uses: svenstaro/upload-release-action@v2
        if: ${{ env.skip_steps != 'true' }}
        with:
          file: llvm_18.linux-x86_64.tar.gz
          asset_name: llvm_18.linux-x86_64.tar.gz
          tag: 'v1.0'
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        if: ${{ env.skip_steps != 'true' }}
        with:
          file: clang-format_18.linux-x86_64.tar.gz
          asset_name: clang-format_18.linux-x86_64.tar.gz
          tag: 'v1.0'
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        if: ${{ env.skip_steps != 'true' }}
        with:
          file: lld_18.linux-x86_64.tar.gz
          asset_name: lld_18.linux-x86_64.tar.gz
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
